### ISSUE TITLE
go mod not found

### ISSUE THREAD

**Issue by higker** [wasmerio/wasmer-go#170]
**The go get directory should be changed to**
```bash
go get github.com/wasmerio/go-ext-wasm
```
**There are typos in your document,Can't get it right**
```bash
go get github.com/wasmerio/go-ext-wasm/wasmer
go: found github.com/wasmerio/go-ext-wasm/wasmer in github.com/wasmerio/go-ext-wasm v0.3.1
```

**Comment by jubianchi** [comment]
Hi @higker!

Since we are working on the 1.0.0 release (and finishing a complete rewrite of wasmer-go), the repository name and layout changed.

Now, you have to `go get github.com/wasmerio/wasmer-go/wasmer` (see https://github.com/wasmerio/wasmer-go#install).

I'm closing this issue but feel free to reopen if you still have problem getting wasmer-go working.
