### ISSUE TITLE
【Missing import: `go`.`debug`】 I try to replace the rust in the example with go

### ISSUE THREAD

**Issue by xzyan** [wasmerio/wasmer-go#248]
## Machine

- OS: Ubuntu 20.10 x86_64
- Go: version go1.16.2 linux/amd64
- Wasmer: github.com/wasmerio/wasmer-go v1.0.3

## Export code

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello wasmer.io")
}

//export Sum
func Sum(x, y int) int {
	return x + y
}

/* BUILD:
GOOS=js GOARCH=wasm go build -o simple.wasm
*/
```

## Import code

```go
package main

import (
	_ "embed"
	"fmt"
	"github.com/wasmerio/wasmer-go/wasmer"
)

var instance *wasmer.Instance

//go:embed simple.wasm
var wasmBytes []byte

func init() {
	store := wasmer.NewStore(wasmer.NewEngine())
	module, e := wasmer.NewModule(store, wasmBytes)
	if e != nil {
		panic(e)
	}
	fmt.Printf("Load Wasm Size: %.2fMB\n", float64(len(wasmBytes))/1024/1024)
	instance, e = wasmer.NewInstance(module, wasmer.NewImportObject())
	if e != nil {
		panic(e) // panic: Missing import: `go`.`debug`
	}
}

func main() {
	sum, _ := instance.Exports.GetFunction("Sum")
	result, _ := sum(5, 37)
	fmt.Println(result)
}
```

## ERROR

```
Load Wasm Size: 2.07MB
panic: Missing import: `go`.`debug`

goroutine 1 [running]:
main.init.0()
        /home/.../.../main.go:23 +0x219
exit status 2
```

**Comment by Hywan** [comment]
The Go compiler generates Wasm modules that are designed for the Web only unfortunately. They must be executed with [a `wasm_exec.js` file](https://github.com/golang/go/blob/master/misc/wasm/wasm_exec.js).

If you wish to generate _real_ Wasm modules, please take a look at [TinyGo](https://tinygo.org/). I'm not sure it's still the case today, but in the past, they were able to generate standalone Wasm modules, not tied to the Web or the unfamous `wasm_exec.js` file.

Otherwise, you can use [`go-wasm`](https://github.com/go-wasm-adapter/go-wasm/), which is a port of `wasm_exec.js` written in Go. It's using `wasmer-go` but I'm not sure it uses the latest version. Check https://github.com/wasmerio/wasmer-go/pull/95 to learn more about the entire discussion.

**Comment by nicholasjackson** [comment]
Just a quick comment on some research I am doing into this.

tinygo will successfully build modules that can be used with wasmer-go however you do need to use the `wasi` target not the  `wasm` target.

```shell
tinygo build -o ./module.wasm -target wasi .
```

Great work on wasmer-go I really love the package, super excited about what WASI and WASM are going to bring to create a cross-platform plugin infrastructure for applications.

**Comment by Hywan** [comment]
Thanks for the tips, that's helpful!

**Comment by nicholasjackson** [comment]
I am working through putting a little example app together in Go that is a plugin interface for applications. At present, I only have basic functionality adding some helper functions to pass strings between the functions but it would be nice to add the other Wasi functions. When I get to this I will update the shim from go-adapter.

Technically the Go Wasm target will work with wasmer, as long as the default imports they add to the module for javascript imports were stubbed out as a wasmer.ImportObject. It might be worth just updating go-adapter for Wasi and JS. Pretty sure the Go team will add Wasi support as soon as the spec stabilizes.

**Comment by Hywan** [comment]
Agree.
